"""add payment fields

Revision ID: 0e3064c9a873
Revises: c9d1e2f3a4b5
Create Date: 2026-09-27 15:06:30.767197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e3064c9a873'
down_revision = 'c9d1e2f3a4b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('payment_gateway', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_transaction_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('upi_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_link', sa.String(length=200), nullable=True))
        batch_op.create_check_constraint('ck_invoices_payment_status', "payment_status IN ('Pending', 'Paid', 'Failed', 'Refunded')")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint('ck_invoices_payment_status', type_='check')
        batch_op.drop_column('payment_link')
        batch_op.drop_column('upi_id')
        batch_op.drop_column('payment_date')
        batch_op.drop_column('payment_transaction_id')
        batch_op.drop_column('payment_gateway')
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
